id: tailFileToHttp

stages:
  origin:
    instanceName: FileTail_01
    stageName: FileTail
    configuration:
      filePath: /Users/yooyoungmo/Downloads/test.log
  #processors:
  destinations:
    - instanceName: Trash_01
      stageName: Trash
      configuration:
        type: NULL # ERROR, NULL, STATS_NULL, STATS_DPM_DIRECTLY
    - instanceName: HttpClient_01
      stageName: HttpClient
      configuration:
        httpUrl: http://localhost:9999